### ISSUE TITLE
create api to get category.

### ISSUE THREAD

**Issue by Angemichel12** [Angemichel12/Transport_project#5]

**Comment by Angemichel12** [comment]
Hello Yvette,

I hope this message finds you well.

I am writting this message to ask the progress about the issue you have been assigned to.

**Comment by Uwisoneye** [comment]
i am going to push

**Comment by Uwisoneye** [comment]
hello,
 can you please remind me the steps(n commands) of pushing ? since i cant to see what i wrote last time, i think i did not save the note i took last time

**Comment by Angemichel12** [comment]
Well done, Keep up.

**Comment by Uwisoneye** [comment]
thanks
